import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import morgan from 'morgan';
import { connectMongo } from './mongo.js';
import { router as apiRouter } from './routes/index.js';
const app = express();
app.use(cors());
app.use(express.json({ limit: '5mb' }));
app.use(morgan('dev'));
app.get('/health', (_req, res) => res.json({ ok: true }));
app.use('/api', apiRouter);
const port = process.env.PORT || 8080;
await connectMongo();
app.listen(port, () => console.log(`[mathmentor-mongo] API http://localhost:${port}`));
